---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: djangoproject
  name: djangoproject
  namespace: djangoproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: djangoproject
  template:
    metadata:
      labels:
        app: djangoproject
    spec:
      containers:
        - args:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          env:
            - name: SECRET_KEY
              value: foo
            - name: DJANGOPROJECT_DATA_DIR
              value: ./data
            - name: DJANGO_SETTINGS_MODULE
              value: djangoproject.settings.docker
            - name: SQL_ENGINE
              value: django.db.backends.postgresql
            - name: SQL_DATABASE
              value: djangoproject
            - name: SQL_USER
              value: djangoproject
            - name: SQL_PASSWORD
              value: ${SQL_PASSWORD}
            - name: SQL_HOST
              value: ${SQL_HOST}
            - name: SQL_PORT
              value: "5432"
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          name: djangoproject
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
