name: CI

on:
  push:
    branches: [ "dev" ]
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
    
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: arturtshitoyan1987
          password: dckr_pat_aIS9bP9_RuZRGvS8YP5bu4O1HGg
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arturtshitoyan1987/djangoproject:v1
