name: CI 

on: 
  push:
    branches: [ "dev" ]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build djangoproject image
        run: docker build -t djangoproject:latest .
        
      - name: Login to Nexus repo 
        run: echo "admin" | docker login reg.andranik-sedrakyan.acadevopscourse.xyz -u admin --password-stdin
        
      - name: Tag image
        run: docker tag djangoproject:latest reg.andranik-sedrakyan.acadevopscourse.xyz/djangoproject:latest
        
      - name: Publish Docker image
        run: docker push reg.andranik-sedrakyan.acadevopscourse.xyz/djangoproject:latest
