name: CI-CD 

on: 
  push:
    branches: [ "dev" ]

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  IMAGE_NAME: ${{ secrets.NEXUS_REPO }}/djangoproject
  IMAGE_TAG: ${{ github.sha }}
  SQL_HOST: ${{ secrets.SQL_HOST }}
  SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

jobs:
  CI:
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Login to Nexus repo 
        run: echo ${{ secrets.NEXUS_PASSWORD }} | docker login ${{ secrets.NEXUS_REPO }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin
        
      - name: Build djangoproject image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        
      - name: Publish Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
        
  CD:
    runs-on: self-hosted
    needs: CI
    steps:
      - name: Git clone
        uses: actions/checkout@v3
        
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIARA7T7P4PATPQPN6O   #${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: 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 #${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 #${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Make deployment file
        run: |
          envsubst < djangoproject.yaml > new_djangoproject.yaml
          cat new_djangoproject.yaml

      - name: Deploy djangoproject to aws eks cluster
        run: |
          # aws configure
          # aws configure
          # aws configure
          # # echo -e "[default]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
          # # echo -e "[default]\nregion = ${{ secrets.AWS_DEFAULT_REGION }}" > ~/.aws/config
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}             
          kubectl apply -f new_djangoproject.yaml