name: CI-CD 

on: 
  push:
    branches: [ "dev" ]

env:
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_NAME: ${{ secrets.NEXUS_REPO }}/djangoproject
  IMAGE_TAG: ${{ github.sha }}
  SQL_HOST: ${{ secrets.SQL_HOST }}
  SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

jobs:
  CI:
    runs-on: self-hosted 
    steps:
      - name: Git clone
        uses: actions/checkout@v3
     
      - name: Login to Nexus repo 
        run: echo ${{ secrets.NEXUS_PASSWORD }} | docker login ${{ secrets.NEXUS_REPO }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin
        
      - name: Build djangoproject image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        
      - name: Publish Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
        
  CD:
    runs-on: self-hosted
    needs: CI
    # permissions:
    #   id-token: write
    #   contents: read
    steps:
    
      - name: Git clone 
        uses: actions/checkout@v3

      - name: Make deployment file
        run: |
          envsubst < djangoproject.yaml > new_djangoproject.yaml
          cat new_djangoproject.yaml

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # role-to-assume: arn:aws:iam::070841761566:role/github
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETKEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Deploy djangoproject to aws eks cluster
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}             
          kubectl apply -f new_djangoproject.yaml